### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by PulkitVyasCynsar**

### CODE REVIEW

**Comment by PulkitVyasCynsar** [comment]
@maektwain Need your input on what license we want to add here. I have added the MIT license but we can change that. Aligning with Netlify Open Source's terms only the licenses listed [here ](https://www.netlify.com/legal/open-source-policy#:~:text=Includes%20a%20license%20listed%20on%20the%20Open%20Source%20Initiative%20approved%20license%20list%20or%20a%20Creative%20Commons%20license%20that%20includes%20%E2%80%9Cattribution%E2%80%9D%20or%20places%20the%20work%20in%20the%20public%20domain.)are allowed. Please let me know which one we want

**Comment by maektwain** [comment]
> Netlify

What is the issue are we addressing here, since this is license free or not , I am not sure that if this is the case , let me know maybe we can use some general license , MIT license is little strict !

**Comment by ankapm** [comment]
@pulkitvyas08  @PulkitVyasCynsar  
perhaps The Creative Commons Attribution-ShareAlike 4.0 International Public License ([Creative Commons — Attribution-ShareAlike 4.0 International — CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/legalcode)) for all content hosted on Second Exchange. Until MF license is released.
u might wanna add this definition in Foundation's open source policy also.
https://docs.muellners.info/open-source-policies/open-source-usage-and-delivery-policies

**Comment by PulkitVyasCynsar** [comment]
> @pulkitvyas08 @PulkitVyasCynsar perhaps The Creative Commons Attribution-ShareAlike 4.0 International Public License ([Creative Commons — Attribution-ShareAlike 4.0 International — CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/legalcode)) for all content hosted on Second Exchange. Until MF license is released. u might wanna add this definition in Foundation's open source policy also. https://docs.muellners.info/open-source-policies/open-source-usage-and-delivery-policies

Okay I'll look into this. Thanks!

**Pull request merged**
